### ISSUE TITLE
CNV analysis and reference data 

### ISSUE THREAD

**Issue by nesilin** [kueckelj/SPATA#12]
Hi!

First of all congratulations! SPATA2 seems like a very useful tool. In fact, I'm interested in performing a CNV analysis on my 10X Visium data. Here are some questions that I have:

1) What does `ref_mtr` parameter from the `runCnvAnalysis` function expect? From the explanation of the documentation is not clear to me. In a cancer study scenario, would `ref_mtr = "data-reference/mtr.RDS"` be some normal-adjacent tissue that has also been analyzed with 10x Visium? Is it then okay to subset the spots from the same slide into tumor-area ones and "normal" ones and use the latest as reference?

2) Can the reference matrix be from a matching scRNA-seq experiment of the same samples?

3) To what extend your reference from the [example](https://themilolab.github.io/SPATA2/articles/spata-v2-cnv-analysis.html) can be used as a general reference for other projects? I'm aware that the example data of the tutorials is not available until you publish (as explained [here](https://github.com/theMILOlab/SPATA/issues/8)) but could you please provide me the reference (`mtr.RDS`)?

Thanks!!!

**Comment by heilandd** [comment]
Thank you for your interest. mtr.RDS can also be a count matrix with genes as rownames and spots as colnames. We recommend not to mix single cell data and spots for CNV analysis. It is better to use non-malignant samples, which can either be a ctr sample or extracted from non-malignant areas of your sample (using the segmentation tool). 

To question 1: Is it then okay to subset the spots from the same slide into tumor-area ones and "normal" ones and use the latest as reference?
- Yes, as long as you know that there is no tumor infiltration. I would use  non-malignant samples of the same tissue type. 

To question 2: Can the reference matrix be from a matching scRNA-seq experiment of the same samples?
- You can also deconvolute non-malignant areas to define the percentage of cells (immune, fibroblasts ... ) Based on this data, and the number of cells per spot (use Ilastik and CellProfiler), a spot count matrix can be reconstructed and used as a reference (we will make this method available as soon as our publication is in press). 

For brain, both approaches work similarly. If you use brain we can provide a reference dataset: https://github.com/theMILOlab/SPATA2/blob/master/data/Ref.rda (temporal lobe non-malignant sample Epi-surgery)

To 3: To what extend your reference from the example can be used as a general reference for other projects?
- I would use organ specific references but I never checked. 

`
download.file("https://github.com/theMILOlab/SPATA2/blob/master/data/Ref.rda?raw=true", "Ref.rda")
mat <- load("Ref.rda")
mat$Counts %>%  dim()
mat$annotations_file %>%  head(5)
`

The RunCNV would look like this: 

`
object <- SPATA2::runCnvAnalysis(object,
                             directory_cnv_folder = getwd(),
                             ref_mtr = mat$Counts,
                             ref_annotation = mat$annotations_file)
`

Hope I could help. 

SPATA Team

**Comment by kueckelj** [comment]
Hello @nesilin, 
I have updated SPATA2. The reference data @heilandd refered to with the code chunk 

`download.file("https://github.com/theMILOlab/SPATA2/blob/master/data/Ref.rda?raw=true", "Ref.rda") mat <- load("Ref.rda") mat$Counts %>% dim() mat$annotations_file %>% head(5)`

is now part of the SPATA2 namespace. If you install SPATA2 again you should be able to access it via  `SPATA2::cnv_ref`. It is a list that contains the reference data the function `runCnvAnalysis()` uses by default. Check out its content manually. This probably helps to understand what the reference arguments need. 

Additionally, I have updated the [tutorial](https://themilolab.github.io/SPATA2/articles/spata-v2-cnv-analysis.html) on cnv analysis as well as the documentation of the function `runCnvAnalysis()`. I hope that helps. The cnv analysis part of SPATA2 is still in development. Therefore, if you encounter any errors please let us know. 

Hint: The webpage mistakenly used to lead to this forum (forum of SPATA) to open issues for SPATA2. The link is now updated. Please open new issues [here](https://github.com/theMILOlab/SPATA2/issues).

Best regards 

Jan (SPATA Team)

**Comment by hzongyao** [comment]
Hi
I plan to use package related ref data as reference of inferCNV,I wonder that how to incite this data ?
Thank you!

**Comment by heilandd** [comment]
You can cite the references dataset as part of our latest preprint: https://www.biorxiv.org/content/10.1101/2021.02.16.431475v1

**Comment by AfterDream** [comment]
Hello, I am currently using SPATA2 version 3.1.2. Regarding the runCNV() function, I have the same question: is it possible to conveniently select non-malignant areas from the same slide as the reference? Is there an appropriate function for this?

**Comment by heilandd** [comment]
Dear AfterDream,
Of course this is possible just split your inputs in Tumor and non tumor data and input this as reference in your inferCNV function. The standard input are expression matrix from normal brain samples. The internal reference will significantly improve the CNV calling.
Henrik

Best regards / Mit freundlichen Grüßen

Univ.-Prof. Dr. med. Dieter Henrik Heiland,

Head of the Translational Neurosurgery,
Friedrich-Alexander-University, Erlangen-Nürnberg
Heisenberg Professor
Attending Neurosurgeon, Department of Neurosurgery,
University Clinic Erlangen

Principal Investigator, Microenvironment and Immunology Research Laboratory,
Team Erlangen and Freiburg, themilolab.com

Associated professor (Adjunct), Department of Neurological Surgery,
Northwestern University
________________________________
Von: AfterDream ***@***.***>
Gesendet: Samstag, 16. November 2024 17:19:49
An: theMILOlab/SPATA
Cc: Prof. Dr. Dieter Henrik Heiland; State change
Betreff: Re: [theMILOlab/SPATA] CNV analysis and reference data (#12)


Hello, I am currently using SPATA2 version 3.1.2. Regarding the runCNV() function, I have the same question: is it possible to conveniently select non-malignant areas from the same slide as the reference? Is there an appropriate function for this?

**Comment by kueckelj** [comment]
To be more precise: you use createSpatialSegmenation() to histologically segment the spots into non-tumor and tumor. This functions saves the labels in a grouping variabl. Afterwards you filter the meta data.frame in which the grouping is stored by your non-tumor label. Extract the barcodes and filter the count matrix by these barcodes. You extract the count matrix with getCountMtr(). Use the filtered matrix as input for the reference matrix.
