### ISSUE TITLE
Problems running with SCTransform

### ISSUE THREAD

**Issue by sysulance** [kueckelj/SPATA#5]
Hi SPATA team! Thank you for bringing a such great package for spatial analysis.

I encountered a problem while initiating a SPATA object
I originally run Seurat pipeline to preprocess my data and the code is
```
# original Seurat pipeline
b3 <- Load10X_Spatial(data.dir = 'data/BHT201011_spaceranger-count/B-3',
                      filename = 'B-3_filtered_feature_bc_matrix.h5')
b3 <- SCTransform(b3, assay = "Spatial", return.only.var.genes = FALSE, 
                  verbose = FALSE, do.scale = TRUE,variable.features.n = 3000)
b3 <- RunPCA(b3, assay = "SCT")
b3 <- FindNeighbors(b3, reduction = "pca", dims = 1:23)
b3 <- FindClusters(b3,resolution = 1.5)
b3 <- RunUMAP(b3, reduction = "pca", dims = 1:23)
```

I tried to use SPATA::initiateSpataObject_10X to implementation all these steps and the code see below
```
b3 <-initiateSpataObject_10X(input_paths = c("data/BHT201011_spaceranger-count/B-3"),
                             sample_names = "b3",
                             NormalizeData = FALSE,
                             FindVariableFeatures = FALSE,
                             ScaleData = FALSE,
                             SCTransform = list(return.only.var.genes = FALSE,
                                                do.scale = TRUE,variable.features.n = 3000),
                             RunPCA = list(npcs=50),
                             FindNeighbors = list(dims=1:23),
                             FindClusters = list(resolution=1.5),
                             RunUMAP = list(dims=1:23))
```

Since SCTransform can cover the function of NormalizeData & FindVariableFeatures & ScaleData, I set them all as FALSE. And the object generate from this code pass the validation function.
But then the plotSurface function seems failed for this object.
```
> plotSurface(object = b3,
+             of_sample = "b3",
+             color_to = "seurat_clusters",
+             pt_clrp = "npg",
+             pt_size = 1.5) + labs(color = "Clusters")
Error in object@data@norm_exp[, bc_in_sample] : 
  no 'dimnames' attribute for array
```

It seems the norm_exp slot is empty and then induce the problem. When I gave up using SCTransform, the problem was solved.
Is there any way I can fix that?
And, I would like to ask if a future update will include a way to easily convert a Seurat object to a SPATA object, by which I need not rerun all the analysis again and will greatly improve efficiency.

Thanks again!

**Comment by heilandd** [comment]
Yes, an update including easy switch between Seurat and SPATA is on the way. Until know, all functions are already in the development branch available (https://github.com/theMILOlab/SPATA/tree/development-kueckelj). But be careful the object architecture changes in version two (developmentkueckelj). 


A small mistake in the function checked only the RNA but not SCT slot for scaled data. Here is the correct version, we will update the mistake as soon as possible. .R file as zip file, just source the function.

Thanks for your help!!
[initiateSPATA_v2.R.zip](https://github.com/theMILOlab/SPATA/files/6016847/initiateSPATA_v2.R.zip)

**Comment by heilandd** [comment]
Update for master and development branch is done. Thanks for your help
