### ISSUE TITLE
Failed to install 'SPATA' from GitHub:

### ISSUE THREAD

**Issue by tn00992786** [kueckelj/SPATA#6]
Error: Failed to install 'SPATA' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘htmltools’

After download and install htmltools. 

Run install package again, 

following error exists:

Error: Failed to install 'SPATA' from GitHub:
  (converted from warning) installation of package ‘C:/Users/ADMINI~1/AppData/Local/Temp/Rtmps1NAt2/file3a24513a3960/SPATA_0.1.0.tar.gz’ had non-zero exit status
---

Run the other install code:
base::install.packages("devtools")

if (!requireNamespace("BiocManager", quietly = TRUE)){
      install.packages("BiocManager")
  }

BiocManager::install(c('BiocGenerics', 'DelayedArray', 'DelayedMatrixStats',
                       'limma', 'S4Vectors', 'SingleCellExperiment',
                       'SummarizedExperiment', 'batchelor', 'Matrix.utils'))

devtools::install_github('cole-trapnell-lab/leidenbase')
devtools::install_github('cole-trapnell-lab/monocle3')

devtools::install_github(repo = 'satijalab/seurat', ref = 'develop')

devtools::install_github(repo = "kueckelj/confuns")
devtools::install_github(repo = "theMILOlab/SPATA")

library(SPATA)
----
error:
The downloaded source packages are in
	‘C:\Users\Administrator\AppData\Local\Temp\Rtmps1NAt2\downloaded_packages’
Warning messages:
1: In install.packages(...) :
  installation of package ‘DelayedMatrixStats’ had non-zero exit status
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.0.3\library\00LOCK\fansi\libs\x64\fansi.dll to C:\Program Files\R\R-4.0.3\library\fansi\libs\x64\fansi.dll: Permission denied
3: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.0.3\library\00LOCK\processx\libs\x64\processx.dll to C:\Program Files\R\R-4.0.3\library\processx\libs\x64\processx.dll: Permission denied
4: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.0.3\library\00LOCK\ps\libs\x64\ps.dll to C:\Program Files\R\R-4.0.3\library\ps\libs\x64\ps.dll: Permission denied
5: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘Matrix’ had non-zero exit status
----

Could anyone solve this problem?

Thanks.

**Comment by heilandd** [comment]
From your error it might be an old version of the package 'Matrix' which causes problems. Can you send me your version of Matrix, I can help to avoid this error, or just try an update which requires to remove Matrix first.
