### ISSUE TITLE
Tutorial for CNV analysis

### ISSUE THREAD

**Issue by ccruizm** [kueckelj/SPATA#9]
Good day,

Thanks for developing such a great tool. I have read the manuscript where you used this package and I am interested in detecting CNV patterns on ST data as you did in your research. Is there any chance you can share a tutorial/code on how to do it? I looked at the website but could not find it. 

Thanks in advance!

**Comment by heilandd** [comment]
Hey, thanks for you request. we recently lunched the v2 of Spata which has tutorials for CNV analysis https://themilolab.github.io/SPATA2/articles/spata-v2-cnv-analysis.html

**Comment by ccruizm** [comment]
Thanks! this is great!
